### ISSUE TITLE
Does spylon-kernel support Spark 3.0?

### ISSUE THREAD

**Issue by bobjiang82** [adtech-labs/spylon-kernel#54]
We tried to run spylon notebook with Spark 3.0 and run into the following error. Is Spark 3.0 supported by spylon? Thanks.

Error in calling magic 'init_spark' on cell:
    Java gateway process exited before sending its port number
    args: []
    kwargs: {}
Traceback (most recent call last):
  File "/home/yuzhou/miniconda3/lib/python3.7/site-packages/metakernel/magic.py", line 94, in call_magic
    func(*args, **kwargs)
  File "/home/yuzhou/miniconda3/lib/python3.7/site-packages/spylon_kernel/init_spark_magic.py", line 59, in cell_init_spark
    init_spark(conf=self.env['launcher'], capture_stderr=stderr)
  File "/home/yuzhou/miniconda3/lib/python3.7/site-packages/spylon_kernel/scala_interpreter.py", line 99, in init_spark
    spark_context = conf.spark_context(application_name)
  File "/home/yuzhou/miniconda3/lib/python3.7/site-packages/spylon/spark/launcher.py", line 521, in spark_context
    return pyspark.SparkContext(appName=application_name, conf=spark_conf)
  File "/home/yuzhou/spark/spark/python/pyspark/context.py", line 128, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/yuzhou/spark/spark/python/pyspark/context.py", line 320, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/yuzhou/spark/spark/python/pyspark/java_gateway.py", line 105, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

%%init_spark [--stderr] - starts a SparkContext with a custom
configuration defined using Python code in the body of the cell

Includes a `spylon.spark.launcher.SparkConfiguration` instance
in the variable `launcher`. Looks for an `application_name`
variable to use as the name of the Spark session.

Example
-------
%%init_spark
launcher.jars = ["file://some/jar.jar"]
launcher.master = "local[4]"
launcher.conf.spark.app.name = "My Fancy App"
launcher.conf.spark.executor.cores = 8

Options:
-------
--stderr       Capture stderr in the notebook instead of in the kernel log [default: False]

**Comment by jesinity** [comment]
Spark 2.X is becoming quite old, so the support for SPark 3.0 would be really great!

**Comment by bobjiang82** [comment]
Update:
We figured out how to get it work with Spark 3.0. Example code as below,
```
%%python
import findspark
import os
findspark.init("the/path/to/spark")

```
```
%%init_spark
launcher.num_executors = 10
launcher.executor_cores = 4
launcher.executor_memory = '10g'
launcher.conf.set("spark.app.name", "spylon-spark3.0-test")
```
