### ISSUE TITLE
Unable to install spylon kernel

### ISSUE THREAD

**Issue by yongyct** [adtech-labs/spylon-kernel#56]
When running the below command (after pip install):
`python -m spylon_kernel install`

The command hangs for very long (> 1 hour), with no CLI feedback and I had to ctrl+c the process.

Is anyone else facing the same issue?

I'm using the below versions:
- macOS Catalina
- python = 3.7.9
- spark = 2.4.6
- jupyter = 4.6.3

**Comment by accraze** [comment]
Confirming I am having the same issue on macOS Montery M1

**Comment by bnisly** [comment]
Ctrl-c gives this stacktrace:
`^CTraceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/spylon_kernel/__main__.py", line 7, in <module>
    SpylonKernel.run_as_main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 122, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 847, in launch_instance
    super(MetaKernelApp, cls).launch_instance(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 709, in start
    return self.subapp.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 861, in start
    kernel_spec = self.kernel_class().kernel_json
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/spylon_kernel/scala_kernel.py", line 46, in __init__
    super(SpylonKernel, self).__init__(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 167, in __init__
    self.reload_magics()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 766, in reload_magics
    module.register_magics(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/magics/shell_magic.py", line 114, in register_magics
    kernel.register_magics(ShellMagic)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/_metakernel.py", line 772, in register_magics
    magic = magic_klass(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/magics/shell_magic.py", line 16, in __init__
    self.start_process()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/magics/shell_magic.py", line 64, in start_process
    self.repl = bash()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/replwrap.py", line 317, in bash
    return REPLWrapper(child, prompt_regex, prompt_change_cmd,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/replwrap.py", line 99, in __init__
    self._expect_prompt()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/metakernel/replwrap.py", line 131, in _expect_prompt
    pos = self.child.expect(expects, timeout=timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/expect.py", line 169, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 500, in read_nonblocking
    if (timeout != 0) and select(timeout):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 450, in select
    return select_ignore_interrupts([self.child_fd], [], [], timeout)[0]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py39spark/lib/python3.9/site-packages/pexpect/utils.py", line 143, in select_ignore_interrupts
    return select.select(iwtd, owtd, ewtd, timeout)
KeyboardInterrupt`
